import LoginForm from "@/components/Login/Login";
import { ChakraProvider } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";

const Products = () => {
    return (
        <>
            <Head>
                <title>Sign In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div>
                <ChakraProvider>
                    <LoginForm />
                </ChakraProvider>
            </div>
        </>
    );
};

export default Products;
