import LoginForm from "@/components/Login/Login";
import { Center } from "@chakra-ui/react";
import Head from "next/head";

const Products = () => {
<<<<<<< HEAD
    return (
        <>
            <Head>
                <title>Sign In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div>
                <LoginForm />
            </div>
        </>
    );
=======
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Center flexDirection="column">
          <LoginForm />
        </Center>
      </div>
    </>
  );
>>>>>>> 8df197d018503197513f4f2c11975a6a2fa3a353
};

export default Products;
