import LoginForm from "@/components/Login/Login";
import { Center } from "@chakra-ui/react";
import Head from "next/head";

const Products = () => {
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Center flexDirection="column">
          <LoginForm />
        </Center>
      </div>
    </>
  );
};

export default Products;
