import RegisterForm from "@/components/Register/Register";
import { Center, ChakraProvider } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";

const Products = () => {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Center flexDirection="column">
          <RegisterForm />
        </Center>
      </div>
    </>
  );
};

export default Products;
