import Head from "next/head";
import React from "react";

const Detail = () => {
	return (
		<>
			<Head>
				<title>Product Detail</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<div>Product Detail</div>
		</>
	);
};

export default Detail;
