import Head from "next/head";
import React from "react";

const Cart = () => {
	return (
		<>
			<Head>
				<title>Cart</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<div>Cart</div>
		</>
	);
};

export default Cart;
