import { Center } from "@chakra-ui/react";
import Head from "next/head";

const Profile = () => {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Center flexDirection="column">Profile</Center>
      </div>
    </>
  );
};

export default Profile;
