import Wrapper from "@/components/Navbar/Wrapper";
import ProductCard from "@/components/ProductCard/ProductCard";
import Hero from "@/components/Slider/Hero";
import { Box, Button, Heading, SimpleGrid, Text } from "@chakra-ui/react";
import Head from "next/head";
import { fetchDataFromAPI } from "../helper/api";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Hero />
        <Wrapper>
          <Box
            textAlign={{ base: "left", md: "center" }}
            maxW={800}
            mx="auto"
            my={{ base: "50px", md: "80px" }}
          >
            <Text>Nike Pegasus 40</Text>
            <Heading
              as="h1"
              fontSize={{ base: "5xl", md: "7xl" }}
              fontWeight="extrabold"
              textTransform="uppercase"
              letterSpacing={{ base: -4, md: -6 }}
              mt={-2}
            >
              The World Runs
            </Heading>
            <Heading
              as="h1"
              fontSize={{ base: "5xl", md: "7xl" }}
              fontWeight="extrabold"
              textTransform="uppercase"
              letterSpacing={{ base: -4, md: -6 }}
              mt={-6}
            >
              In Pegasus.
            </Heading>
            <Text py={6}>
              Meet the latest update to the shoe that's been trusted by runners
              of all kinds for four decades.
            </Text>
            <Button
              color="white"
              bg="black"
              colorScheme="blackAlpha"
              rounded={50}
              size="md"
              fontWeight="normal"
            >
              Shop
            </Button>
          </Box>
          <SimpleGrid minChildWidth={400} gap={5} my={14}>
            {products?.map((product) => (
              <ProductCard key={product?.id} data={product} />
            ))}
          </SimpleGrid>
        </Wrapper>
      </Box>
    </>
  );
}

export async function getStaticProps() {
  const products = await fetchDataFromAPI("/product");
  return {
    props: {
      products,
    },
  };
}
