import Wrapper from "@/components/Navbar/Wrapper";
import { useAuth } from "@/modules/context/authCotext";
import { Box, Center, Flex, Text, VStack } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";

const Success = () => {
  return (
    <>
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Flex minHeight={650} alignItems="center">
          <Wrapper>
            <VStack
              maxWidth={600}
              rounded="lg"
              p={5}
              border={1}
              borderColor="black"
              mx="auto"
            >
              <Box fontSize="2xl" fontWeight="bold">
                Thanks for shopping with us!
              </Box>
              <Box fontSize="lg" fontWeight="semibold" mt={2}>
                Your order has been placed successfully.
              </Box>
              <Link href="/">
                <Text fontWeight="bold" mt={5} colorScheme="blackAlpha">
                  Continue Shopping
                </Text>
              </Link>
            </VStack>
          </Wrapper>
        </Flex>
      </div>
    </>
  );
};

export default Success;
