import { Center } from "@chakra-ui/react";
import Head from "next/head";

const Success = () => {
  return (
    <>
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Center flexDirection="column">Success</Center>
      </div>
    </>
  );
};

export default Success;
