import Head from "next/head";
import React from "react";

const Products = () => {
	return (
		<>
			<Head>
				<title>Products</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<div>Products</div>
		</>
	);
};

export default Products;
